version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=UTC
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 